knp_paginator:
  page_range: 5
  default_options:
    page_name: page
    sort_field_name: sort
    sort_direction_name: direction
    distinct: true
  template:
    pagination: '@PLejeuneCore/knp/pagination/foundation.html.twig'
