version: '3.2'

services:
  database:
    image: mariadb:10.3
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - database:/var/lib/mysql

  http:
    image: nginx:1-alpine
    expose:
      - "80"
      - "443"
    depends_on:
    - php
    volumes:
    - ./.docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    - ./public/:/srv/public/

  php:
    image: registry.gitlab.com/pierrelejeune/docker-symfony/php
    build:
      context: ./.docker/php
      dockerfile: Dockerfile
    working_dir: /srv
    volumes:
      - ./:/srv/
    tty: true

  node:
    image: registry.gitlab.com/pierrelejeune/docker-symfony/node
    build:
      context: ./.docker/node
      dockerfile: Dockerfile
    working_dir: /srv
    volumes:
      - ./:/srv/

volumes:
  database: ~
