App\Entity\Media:
    type: entity
    table: media
    repositoryClass: App\Repository\MediaRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
            nullable: false
        description:
            type: text
            nullable: true
        category:
            type: string
            length: 50
            nullable: true
        poster:
            type: string
            length: 255
            nullable: true
        backdrop:
            type: string
            length: 255
            nullable: true
        updated:
            type: datetime
            nullable: true
        status:
            type: string
            length: 255
            nullable: true
        releaseDate:
            type: date
            nullable: true
        averageNote:
            type: float
            nullable: true
        source:
            type: string
            nullable: true
        sourceId:
            type: integer
            nullable: true

    manyToMany:
        genres:
            targetEntity: App\Entity\Genre
            joinColumn:
                name: media_id
                referencedColumnName: id
            inverseJoinColumns:
                name: group_id
                referencedColumnName: id

    lifecycleCallbacks: {  }
