App\Entity\SourceWatch:
    type: entity
    table: source_watch
    repositoryClass: App\Repository\SourceWatchRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 50
            nullable: false
        url:
            type: string
            length: 255
            nullable: false

    manyToOne:
        source:
            targetEntity: App\Entity\Source
            joinColumn:
                name: source_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
