App\Entity\User:
    type: entity
    table: user
    repositoryClass: App\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 50
            nullable: false
            unique: true
        email:
            type: string
            length: 255
            nullable: false
            unique: true
        password:
            type: string
            length: 255
            nullable: false
        roles:
            type: simple_array
        created:
            type: datetime
        updated:
            type: datetime
            nullable: true
    lifecycleCallbacks:
        prePersist: [onPrePersist]
        preUpdate: [onPreUpdate]
